config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :surveys
	root 'surveys#index'
	get '/thank', to: "surveys#thank"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
	serialize :rating, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

    # called from index
	def new
		@survey=Survey.new
	end

    # redirects to Thank You page
	def thank
	end

    # called when the Submit button is clicked
	def create
		@survey=Survey.new(survey_params)
   		if @survey.save
     	  flash[:notice]="Thank you for answering this survey!"
     	  flash[:color]="valid"
        redirect_to :action => 'thank'
    	else
     	  flash[:notice]="Please answer all fields."
     	  flash[:color]="invalid"
        render :new
    	end	
	end 

	private
	def survey_params
    	params.require(:survey).permit(:name,:user_type)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/index.html.erb
<h1>Survey</h1>

<h3>Dear Sir/Madam,</h3>
					
<h3>Greetings! We are students from the Service, Science, and Software Engineering (S3) laboratory in the Department of Computer Science conducting our thesis for the University Human Resource Information System (UHRIS). With that, we are asking for your help in evaluating the system by answering this questionnaire.</h3>

<h3>This questionnaire has been designed for weighing software quality factors of a UHRIS. In our research, we have identified six quality factors that are important in evaluating the system: Functionality, Reliability, Usability, Efficiency, Maintainability and Portability. These quality factors will be further divided into quality subfactors composing the 2nd level of our quality model. The weighing of the quality subfactors will be done through the next survey after we have identified which subfactors will be used for UHRIS. Your opinion helps us determine the degree of importance of them.</h3>

<h3>The goal of the questionnaire is to obtain the strength of preference of quality factors using Mutual Comparison Method, in which each quality factor is compared to each other. In the second survey, the relative importance of quality subfactors under the common quality factors will be obtained.</h3>
					
<h3>Thank you very much for your attention and time.</h3>
			

<h3>Regards,</h3>


<h3>___________________</h3>
<h3>Treacy Evangelista</h3>


<h3>___________________</h3>
<h3>Cyan Villarin</h3>


<h3>___________________</h3>
<h3>Roy Vincent Canseco</h3>
<h3>Thesis Adviser</h3>

<%= link_to 'Take the Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>Take Survey</h1>

<%= form_for(@survey) do |form| %>
	<p>
		<%= form.label :name %>&nbsp;
		<%= form.text_field :name %>
	</p>

	<p>
		I will answer as a...<br>

		<!-- Question: user_type is saved as 't' in the database? Why? -->

		<%= form.radio_button :user_type, 'developer', :checked => true %> 
		Developer
		<%= form.radio_button :user_type, 'user' %>
		User
	</p>


<p>
	The following are the definitions of each quality factor as stated in the journal <em>“”</em> to give a better understanding:<br>
<ul>
	<li><strong>Functional Suitability</strong></li>
	<li><strong>Reliability</strong></li>
	<li><strong>Performance Efficiency</strong></li>
	<li><strong>Operability</strong></li>
	<li><strong>Security</strong></li>
	<li><strong>Compatibility</strong></li>
	<li><strong>Maintainability</strong></li>
	<li><strong>Transferability</strong></li>
</ul>
	In each row of the table below, which quality factor is more important with respect to a UHRIS applications? And how strongly?<br>Please check the table below and rate the factors from 1 to 5. If you believe the second quality is more important than the first quality factor, add a negative to your rating to signify your preference.<br>

	(5 = First Quality Factor is way more important than Second Quality Factor)<br>
	(0 = First Quality Factor is of equal importance with the Second Quality Factor)<br>
	(-5 = Second Quality Factor is way more important than First Quality Factor)
</p>


<table>
	<thead>
		<tr> 
			<th style="border:1px solid black">First Quality Factor</th>
			<th style="border:1px solid black">Second Quality Factor</th>
			<th style="border:1px solid black">Stregth of Preference (-5 to 5)</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Reliability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Performance Efficiency</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Operatability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Security</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Compatibility</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Functional Suitability</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Performance Efficiency</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Operability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Security</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Compatibility</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Reliability</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Performance Efficiency</td>
			<td style="border:1px solid black">Operability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Performance Efficiency</td>
			<td style="border:1px solid black">Security</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Performance Efficiency</td>
			<td style="border:1px solid black">Compatibility</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Performance Efficiency</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Performance Efficiency</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Operability</td>
			<td style="border:1px solid black">Security</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Operability</td>
			<td style="border:1px solid black">Compatibility</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Operability</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Operability</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Security</td>
			<td style="border:1px solid black">Compatibility</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Security</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Security</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Compatibility</td>
			<td style="border:1px solid black">Maintainability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Compatibility</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>

		<tr>
			<td style="border:1px solid black">Maintainability</td>
			<td style="border:1px solid black">Transferability</td>

		</tr>


	</tbody>
</table>

<br>

<%= form.submit %>
<br>

<% end %>

app/views/surveys/thank.html.erb
<h1>Thank you!</h1>